package org.prosolo.common.domainmodel.events;

public enum EventType {
	AcceptRecommendation, 
	Assessment, 
	ChangeVisibility, 
	Like,
	RemoveLike,
	RemoveDislike,
	Dislike,
	Post,
	TwitterPost,
	AddNote,
	PostShare,
	Comment, 
	Comment_Reply,
	Tag, 
	Attach,
	AttachAll,
	Detach,
	Edit, 
	Edit_Profile, 
	Edit_Draft,
	Create,
	Create_Manager,
	Create_Draft,
	Delete,
	Delete_Draft,
	Follow,
	Unfollow,
	Registered,
	Account_Activated,
	MarkAsFavourite, 
	FollowEvent, 
	Create_recommendation, 
	DISMISS_RECOMMENDATION,
	Completion, 
	NotCompleted,
	GiveRecognition, 
	StatusUpdate,
	ChangeProgress, 
	RequestSent,
	Event,
	CommentsEnabled,
	CommentsDisabled,
	
	UpdatedSocialNetworks,
	
	// activities
	AssignmentRemoved,
	AssignmentUploaded,
	
	// content types
	FileUploaded,
	LinkAdded,
	
	// requests
	JoinedGoal,
	JOIN_GOAL_REQUEST,
	JOIN_GOAL_REQUEST_APPROVED,
	JOIN_GOAL_REQUEST_DENIED,
	JOIN_GOAL_REQUEST_IGNORED,
	JOIN_GOAL_INVITATION,
	JOIN_GOAL_INVITATION_ACCEPTED,

	SEND_MESSAGE,
	START_MESSAGE_THREAD, 
	READ_MESSAGE_THREAD, 
	UPDATE_MESSAGE_THREAD,
	
	ENROLL_COURSE,
	ENROLL_COMPETENCE,
	COURSE_WITHDRAWN,
	CREDENTIAL_COMPLETED, 
	
	NAVIGATE, SERVICEUSE, LOGIN, SESSIONENDED, LOGOUT, 
	
	FILTER_CHANGE, HIDE_SOCIAL_ACTIVITY, UNFOLLOW_HASHTAGS,
	
	CREATE_PERSONAL_SCHEDULE, 
	CREATE_PERSONAL_SCHEDULE_ACCEPTED, 
	SELECT_GOAL, 
	SELECT_COMPETENCE, 
	GOAL_WALL_FILTER, 
	COMPETENCES_COMPARE, 
	ACTIVITIES_COMPARE, 
	NEW_COMPETENCE_DIALOG, 
	INTERESTS_UPDATED, 
	SEND_TO_LEARN, 
	ACTIVATE_COURSE, 
	ACTIVITY_REPORT_AVAILABLE, 
	MENTIONED, UPDATE_HASHTAGS, UPDATE_TAGS, PostUpdate,
	HASHTAG_ENABLED, HASHTAG_DISABLED, ARCHIVE_GOAL,
	DIGEST_FILTER_UPDATED,
	
	//this activity exists in MOOC logs for some reasons
	HIDE_ACTIVITY,
	COMMENT_CANCEL,
	
	INSTRUCTOR_ASSIGNED_TO_CREDENTIAL,
	INSTRUCTOR_REMOVED_FROM_CREDENTIAL,
	STUDENT_ASSIGNED_TO_INSTRUCTOR,
	STUDENT_UNASSIGNED_FROM_INSTRUCTOR,
	STUDENT_REASSIGNED_TO_INSTRUCTOR,
	
	USER_ROLES_UPDATED,

	USER_ASSIGNED_TO_ORGANIZATION,
	USER_REMOVED_FROM_ORGANIZATION,
	
	Bookmark,
	RemoveBookmark, 
	AssessmentRequested, 
	AssessmentApproved,
	AssessmentComment, 
	AnnouncementPublished,
	ASSESSMENT_REQUEST_DECLINED,
	ASSESSMENT_REQUEST_ACCEPTED,
	ASSESSOR_WITHDREW_FROM_ASSESSMENT,
	ASSESSOR_ASSIGNED_TO_ASSESSMENT,
	
	Typed_Response_Posted,
	Typed_Response_Edit,
	
	SCHEDULED_VISIBILITY_UPDATE,
	CANCEL_SCHEDULED_VISIBILITY_UPDATE,
	ADD_USER_TO_GROUP,
	REMOVE_USER_FROM_GROUP,
	RESOURCE_VISIBILITY_CHANGE,
	USER_GROUP_ADDED_TO_RESOURCE,
	USER_GROUP_REMOVED_FROM_RESOURCE,
	//RESOURCE_USER_GROUP_PRIVILEGE_CHANGE,
	//users are added and/or removed to the group
	USER_GROUP_CHANGE,
	VISIBLE_TO_ALL_CHANGED,
	STATUS_CHANGED,
	ADD_INSTRUCTOR_TO_CREDENTIAL,
	REMOVE_INSTRUCTOR_FROM_CREDENTIAL,
	GRADE_ADDED,
	ASSESSED_BY_AUTO_GRADING,

	
	PAGE_OPENED,
	
	ARCHIVE,
	RESTORE,

	OWNER_CHANGE,

	ADD_USER_TO_UNIT,
	REMOVE_USER_FROM_UNIT,

	ADD_CREDENTIAL_TO_UNIT,
	REMOVE_CREDENTIAL_FROM_UNIT,
	ADD_COMPETENCE_TO_UNIT,
	REMOVE_COMPETENCE_FROM_UNIT,
	ADD_RUBRIC_TO_UNIT,
	REMOVE_RUBRIC_FROM_UNIT,
	UPDATE_DELIVERY_TIMES,
	LEARNING_STAGE_UPDATE,
	CREDENTIAL_CATEGORY_UPDATE;
	
	private String customText;
	
	private EventType(String customText) {
		this.customText = customText;
	}
	    
	private EventType() { }
	
	public String getCustomText() {
		return customText;
	}

	public EventType setCustomText(String customText){
		this.customText = customText;
		return this;
	}
}
