package org.prosolo.bigdata.common.events.pojo;
/**
@author Zoran Jeremic Apr 20, 2015
 *
 */

public enum DataName {
	USERACTIVITY, ACTIVITYINTERACTION, TARGETCOMPETENCEACTIVITIES, USERLEARNINGGOALACTIVITY, MOSTACTIVEUSERSFORLEARNINGGOALBYDATE, 
	FAILEDFEEDS,
	//Used for DataType.PROCESS
	UPDATEHASHTAGS, UPDATETWITTERUSER, EVENTDAILYCOUNT, USEREVENTDAILYCOUNT, INSTANCELOGGEDUSERSCOUNT, DISABLEDHASHTAGS
}
