package org.prosolo.services.logging;

/**
 * @author Zoran Jeremic 2013-10-07
 *
 */

public enum ComponentName {
	DIGGEST, 
	REMINDER_DIALOG, 
	COMPETENCE_DIALOG, 
	PEOPLE_LIST_DIALOG,
	POST_DIALOG,
	ACTIVITY_DIALOG, 
	GOAL_DIALOG, 
	REQUEST_TO_JOIN_GOAL_DIALOG, 
	FREE_TO_JOIN_GOAL_DIALOG, 
	USER_DIALOG, 
	USER_LOCATION_DIALOG, 
	GLOBAL_SEARCH, 
	COURSES, 
	COMMUNICATIONS, 
	NOTIFICATIONS, 
	INBOX, 
	SEARCH_REMINDERS,
	SEARCH_ACTIVITIES,
	SEARCH_PEOPLE, 
	SEARCH_GOALS, 
	SEARCH_COMPETENCES, 
	SEARCH_HASHTAGS, 
	SEARCH_COURSE, 
	SEARCH_EXTERNAL_TOOLS, 
	SEARCH_TAGS,
	
	MOUSE_CLICK,
	
	COMPETENCE_ANALYTICS_DIALOG,
	ACTIVITY_ANALYTICS_DIALOG,
	GOAL_ANALYTICS_DIALOG,

	NEW_GOAL_DIALOG,
	DELETE_GOAL_DIALOG,
	ACTIVATE_COURSE_DIALOG, 
	WITHDRAW_COURSE_DIALOG, 
	INVITE_GOAL_COLLABORATOR_DIALOG, 
	ASK_FOR_EVALUATION_DIALOG,
	EVALUATION_LIST_DIALOG,
	BADGE_LIST_DIALOG,
	ACTIVITY_LIST_DIALOG,
	DELETE_COMPETENCE_DIALOG, 
	SEND_TO_GOALS_DIALOG, 
	DELETE_EXTERNAL_CREDIT_DIALOG, 
	DIRECT_MESSAGE_DIALOG,
	TUTORIAL_PLAYED,
	ADD_TO_COMPETENCE_DIALOG,
	ADD_TO_GOAL_DIALOG,
	
	
	// to delete. I will not remove it now as there might be used in the database
	COMPETENCEDIALOG, 
	PEOPLELISTDIALOG,
	ACTIVITYDIALOG, 
	GOALDIALOG, 
	USERDIALOG, 
	USERLOCATIONDIALOG, 
	GLOBALSEARCH, 
	SEARCHPEOPLE, 
	SEARCHGOALS, 
	SEARCHCOMPETENCES, 
	SEARCHCOURSE, 
	SEARCHTAGS,
	MOUSECLICK,
}
